# This model push all variables

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
# Importing the dataset
data = pd.read_csv('online.csv')
data.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [3]:
cols = data.shape[1]
X = data.iloc[:,:cols-2].values
y = data.iloc[:,cols-1 : cols].values

In [4]:
cols

5

In [5]:
X

array([[114523.61, 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34,  91391.77, 366168.42],
       [131876.9 ,  99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [165349.2 , 122616.84, 261776.23],
       [ 78013.11, 121597.55, 264346.06],
       [ 94657.16, 145077.58, 282574.31],
       [ 91749.16, 114175.79, 294919.57],
       [ 86419.7 , 153514.11,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78389.47, 153773.43, 299737.29],
       [ 73994.56, 122782.75, 303319.26],
       [ 67532.53, 105751.03, 3047

## Encoding categorical data

In [6]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Marketing Spend  50 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        50 non-null     float64
 3   Area             50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [8]:
data.corr()

Marketing Spend  Administration  Transport    Profit
Marketing Spend         1.000000        0.230437   0.685442  0.937948
Administration          0.230437        1.000000  -0.032154  0.200717
Transport               0.685442       -0.032154   1.000000  0.747766
Profit                  0.937948        0.200717   0.747766  1.000000

## avoiding dummy variable trap

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
sc_X_train = scaler.fit_transform(X_train)
sc_X_test = scaler.transform(X_test)


In [11]:
sc_X_test

array([[ 0.30245367,  0.52942836,  0.14916233],
       [-0.82734624, -1.40769369, -0.53560477],
       [-0.33181874, -0.20294703, -1.27505783],
       [-1.62147425,  0.11103854, -2.06176266],
       [ 0.35879726,  0.88291223,  0.41286919],
       [-1.63116196, -2.56004955, -2.07854935],
       [-0.04987791,  0.84817808, -0.89664846],
       [-0.2753597 ,  0.67912498, -0.86215204],
       [-0.30191325,  0.29793642, -1.67222209],
       [ 0.18462534,  1.19412269, -2.07854935]])

In [12]:
sc_X_train.shape[1]

3

In [13]:
import os

import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Activation, Dropout, Input,InputLayer

from keras.models import Sequential 

In [14]:
from keras.optimizers import SGD
opt = SGD(learning_rate=0.1)

model = Sequential()
model.add(InputLayer(input_shape = sc_X_train.shape[1], ))
# model.add(Dense(64, activation = 'relu'))
# model.add(Dense(64, activation = 'relu'))
model.add(Dense(1, activation='linear'))

model.compile(optimizer=opt,
                loss='mean_squared_error', metrics=['accuracy'])

# Display the model's architecture
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [15]:
history = model.fit(sc_X_train, y_train, verbose = 1, epochs=70, validation_data=(sc_X_test, y_test))

Epoch 1/70
2/2 [==============================] - 1s 288ms/step - loss: 14089963520.0000 - accuracy: 0.0000e+00 - val_loss: 5498159104.0000 - val_accuracy: 0.0000e+00
Epoch 2/70
2/2 [==============================] - 0s 40ms/step - loss: 5908388352.0000 - accuracy: 0.0000e+00 - val_loss: 2719786240.0000 - val_accuracy: 0.0000e+00
Epoch 3/70
2/2 [==============================] - 0s 40ms/step - loss: 2580658432.0000 - accuracy: 0.0000e+00 - val_loss: 1425220992.0000 - val_accuracy: 0.0000e+00
Epoch 4/70
2/2 [==============================] - 0s 32ms/step - loss: 1179713536.0000 - accuracy: 0.0000e+00 - val_loss: 1057475584.0000 - val_accuracy: 0.0000e+00
Epoch 5/70
2/2 [==============================] - 0s 40ms/step - loss: 561051328.0000 - accuracy: 0.0000e+00 - val_loss: 709154368.0000 - val_accuracy: 0.0000e+00
Epoch 6/70
2/2 [==============================] - 0s 40ms/step - loss: 357566400.0000 - accuracy: 0.0000e+00 - val_loss: 502769568.0000 - val_accuracy: 0.0000e+00
Epoch 7/70
2

In [16]:
prediction_test = model.predict(sc_X_test)

print(y_test)
print('---------------')
print(prediction_test)

1/1 [==============================] - 0s 120ms/step
[[134307.35]
 [ 81005.76]
 [ 99937.59]
 [ 64926.08]
 [125370.37]
 [ 35673.41]
 [105733.54]
 [107404.34]
 [ 97427.84]
 [122776.86]]
---------------
[[127444.99 ]
 [ 82196.305]
 [ 90171.45 ]
 [ 39170.836]
 [132416.38 ]
 [ 37912.47 ]
 [104011.625]
 [ 97012.53 ]
 [ 86714.34 ]
 [ 98145.03 ]]


In [17]:
model.compile(optimizer=opt, loss='mean_squared_error', metrics=['accuracy'])
model.evaluate(X,y)

2/2 [==============================] - 0s 8ms/step - loss: 30649190089465266176.0000 - accuracy: 0.0000e+00


[3.0649190089465266e+19, 0.0]

In [18]:
# Calling `save('my_model.h5')` creates a h5 file `my_model.h5`.
model.save("my_h5_model.h5")

# It can be used to reconstruct the model identically.
reconstructed_model = keras.models.load_model("my_h5_model.h5")

In [20]:
reconstructed_model.predict([[12000,34000,46457]])

1/1 [==============================] - 0s 119ms/step


array([[9.355831e+08]], dtype=float32)

In [22]:
prediction_test = reconstructed_model.predict(sc_X_test)

print(y_test)
print('---------------')
print(prediction_test)

1/1 [==============================] - 0s 96ms/step
[[134307.35]
 [ 81005.76]
 [ 99937.59]
 [ 64926.08]
 [125370.37]
 [ 35673.41]
 [105733.54]
 [107404.34]
 [ 97427.84]
 [122776.86]]
---------------
[[127444.99 ]
 [ 82196.305]
 [ 90171.45 ]
 [ 39170.836]
 [132416.38 ]
 [ 37912.47 ]
 [104011.625]
 [ 97012.53 ]
 [ 86714.34 ]
 [ 98145.03 ]]
